# Generated by Django 4.0.4 on 2023-03-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPersonalDetails',
            fields=[
                ('Email_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=10)),
                ('DOB', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=25)),
                ('area', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
