# Generated by Django 4.0.4 on 2023-02-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('Emailid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=40)),
                ('Area', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='personalDetails',
            fields=[
                ('Emailid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('personal_phone_no', models.CharField(max_length=10)),
                ('Student_name', models.CharField(max_length=20)),
                ('Father_name', models.CharField(max_length=20)),
                ('Mother_name', models.CharField(max_length=20)),
                ('Phone_no', models.CharField(max_length=10)),
                ('DOB', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDetails',
            fields=[
                ('Emailid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Student_ID', models.CharField(max_length=20)),
                ('Roll_no', models.CharField(max_length=10)),
                ('Class', models.CharField(max_length=5)),
                ('Stream', models.CharField(max_length=15)),
                ('Section', models.CharField(max_length=1)),
            ],
        ),
    ]
